## TensorFlow: A Short Introduction

In [11]:
import numpy as np
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

def get_weights(n_features, n_labels):
    """
    Return TensorFlow weights
    :param n_features: Number of features
    :param n_labels: Number of labels
    :return: TensorFlow weights
    """
    # TODO: Return weights
    return tf.Variable(tf.truncated_normal((n_features, n_labels)))


def get_biases(n_labels):
    """
    Return TensorFlow bias
    :param n_labels: Number of labels
    :return: TensorFlow bias
    """
    # TODO: Return biases
    return tf.Variable(tf.zeros(n_labels))


def linear(_input, w, b):
    """
    Return linear function in TensorFlow
    :param input: TensorFlow input
    :param w: TensorFlow weights
    :param b: TensorFlow biases
    :return: TensorFlow linear function
    """
    # TODO: Linear Function (xW + b)
    return tf.add(tf.matmul(_input, w), b)

In [43]:
def mnist_features_labels(n_labels):
    """
    Gets the first <n> labels from the MNIST dataset
    :param n_labels: Number of labels to use
    :return: Tuple of feature list and label list
    """
    mnist_features = []
    mnist_labels = []

    mnist = input_data.read_data_sets('./datasets/ud730/mnist', one_hot=True)

    # In order to make quizzes run faster, we're only looking at 10000 images
    for mnist_feature, mnist_label in zip(*mnist.train.next_batch(10000)):

        # Add features and labels if it's for the first <n>th labels
        if mnist_label[:n_labels].any():
            mnist_features.append(mnist_feature)
            mnist_labels.append(mnist_label[:n_labels])

    return mnist_features, mnist_labels

def run_lin_func_test():
    # Number of features (28*28 image is 784 features)
    n_features = 784
    # Number of labels
    n_labels = 3

    # Features and Labels
    features = tf.placeholder(tf.float32)
    labels = tf.placeholder(tf.float32)

    # Weights and Biases
    w = get_weights(n_features, n_labels)
    b = get_biases(n_labels)

    # Linear Function xW + b
    logits = linear(features, w, b)

    # Training data
    train_features, train_labels = mnist_features_labels(n_labels)

    with tf.Session() as session:
        # TODO: Initialize session variables
        session.run(tf.global_variables_initializer())

        # Softmax
        prediction = tf.nn.softmax(logits)

        # Cross entropy
        # This quantifies how far off the predictions were.
        # You'll learn more about this in future lessons.
        cross_entropy = -tf.reduce_sum(
            labels * tf.log(prediction), reduction_indices=1)

        # Training loss
        # You'll learn more about this in future lessons.
        loss = tf.reduce_mean(cross_entropy)

        # Rate at which the weights are changed
        # You'll learn more about this in future lessons.
        learning_rate = 0.08

        # Gradient Descent
        # This is the method used to train the model
        # You'll learn more about this in future lessons.
        optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

        # Run optimizer and get loss
        _, loss = session.run(
            [optimizer, loss],
            feed_dict={features: train_features,
                       labels: train_labels})
        
        return loss
    

print('Loss: {}'.format(run_lin_func_test()))

Extracting ./datasets/ud730/mnist/train-images-idx3-ubyte.gz
Extracting ./datasets/ud730/mnist/train-labels-idx1-ubyte.gz
Extracting ./datasets/ud730/mnist/t10k-images-idx3-ubyte.gz
Extracting ./datasets/ud730/mnist/t10k-labels-idx1-ubyte.gz
Loss: 5.444807052612305


In [8]:
# Softmax normalization in TF. 
def run_softmax():
    output = None
    logit_data = [2.0, 1.0, 0.1]
    logits = tf.placeholder(tf.float32)

    # TODO: Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)

    with tf.Session() as sess:
        # TODO: Feed in the logit data
        output = sess.run(softmax, feed_dict={logits: logit_data})

    return output

In [9]:
# Softmax normalization in TF. 
def run_softmax():
    output = None
    logit_data = [2.0, 1.0, 0.1]
    logits = tf.placeholder(tf.float32)

    # TODO: Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)

    with tf.Session() as sess:
        # TODO: Feed in the logit data
        output = sess.run(softmax, feed_dict={logits: logit_data})

    return output

print(run_softmax())

[ 0.65900117  0.24243298  0.09856589]


In [42]:
# OneHotEncoder using sklearn
from sklearn import preprocessing
def one_hot_encoding():
    # Example labels
    labels = np.array([1, 5, 3, 2, 1, 4, 2, 1, 3])

    # Create the encoder
    lb = preprocessing.LabelBinarizer()

    # Here the encoder finds the classes and assigns one-hot vectors
    lb.fit(labels)

    # And finally, transform the labels into one-hot encoded vectors
    return lb.transform(labels)

print(one_hot_encoding())

[[1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]]


In [39]:
# Cross Entropy in TensorFlow
def tf_cross_entropy():
    softmax_data = [0.7, 0.2, 0.1]
    one_hot_data = [1.0, 0.0, 0.0]

    softmax = tf.placeholder(tf.float32)
    one_hot = tf.placeholder(tf.float32)
    
    # TODO: Print cross entropy from session
    idx_mul = tf.multiply(one_hot, tf.log(softmax))
    cross_entropy = -1.0 * tf.reduce_sum(idx_mul)
    
    with tf.Session() as sess:
        # calc = -1.0 * tf.reduce_sum(tf.matmul(one_hot, softmax))
        output = sess.run(cross_entropy, feed_dict={one_hot:one_hot_data, softmax:softmax_data})
    
    return output

print(tf_cross_entropy())

0.356675


### Always worry about the calculation between large and small values:

In [44]:
def what_the_hell():
    a = 1000000000
    for i in range(1000000):
        a = a + 1e-6
    return (a - 1000000000)

print(what_the_hell())

0.95367431640625
